# edpearOS Calamares Installer — Main Configuration
# https://github.com/calamares/calamares/wiki/Develop-Guide
---
modules-search: [ local, /etc/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - student-setup
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - packages
    - grubcfg
    - bootloader
    - postcfg
    - umount
  - show:
    - finished

branding: edpearos

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
