#
# edpearOS pacman.conf for archiso builds
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Chaotic-AUR — provides pre-built AUR packages (obsidian, calamares, etc.)
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
