# Calamares finished module
---
restartNowEnabled: true
restartNowChecked: true
restartNowCommand: "systemctl -i reboot"
notifyOnFinished: true

restartNowMessage: "edpearOS has been installed! Remove the USB drive and press Restart to boot into your new system."
