# Calamares post-install configuration script
---
keyrings:
    - archlinux

script:
    - command: "/etc/calamares/modules/student-setup-script.sh @@ROOT@@"
      timeout: 300
    - command: "cp -r /etc/edpearos @@ROOT@@/etc/edpearos"
      timeout: 30
    - command: "cp /usr/local/bin/edpear-focus @@ROOT@@/usr/local/bin/edpear-focus"
      timeout: 10
    - command: "cp /usr/local/bin/edpear-welcome @@ROOT@@/usr/local/bin/edpear-welcome"
      timeout: 10
    - command: "chmod 755 @@ROOT@@/usr/local/bin/edpear-focus @@ROOT@@/usr/local/bin/edpear-welcome"
      timeout: 10
